In [1]:
from google.colab import files
uploaded = files.upload()

Saving Madedata1.csv to Madedata1.csv


In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.linear_model import LogisticRegression

In [51]:
df = pd.read_csv('Madedata1.csv')

In [52]:
df.shape

(2499, 12)

In [53]:
df.head()

Country  Age  ... Contact_with_covid_patient  Infected
0               China   10  ...                         No         0
1               Italy   20  ...                  Not known         1
2                Iran   55  ...                         No         0
3  Republic of Korean   37  ...                        Yes         1
4              France   45  ...                        Yes         1

[5 rows x 12 columns]

In [54]:
# df = df.iloc[:,1:]
df.drop(columns=['Country'], inplace=True)

In [55]:
df.head()

Age       Gender  fever  ...  Severity  Contact_with_covid_patient  Infected
0   10         Male    102  ...      Mild                          No         0
1   20         Male    103  ...  Moderate                   Not known         1
2   55  Transgender     99  ...    Severe                          No         0
3   37       Female    100  ...      Mild                         Yes         1
4   45         Male    101  ...  Moderate                         Yes         1

[5 rows x 11 columns]

In [56]:
pd.value_counts(df['Gender'])

Male           1257
Female         1208
Transgender      34
Name: Gender, dtype: int64

In [57]:
pd.value_counts(df['Severity'])

Mild        1591
Moderate     525
Severe       383
Name: Severity, dtype: int64

In [58]:
pd.value_counts(df['Contact_with_covid_patient'])

No           1203
Yes           638
Not known     633
yes            25
Name: Contact_with_covid_patient, dtype: int64

In [59]:
df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower() 

In [60]:
pd.value_counts(df['Contact_with_covid_patient'])

no           1203
yes           663
not known     633
Name: Contact_with_covid_patient, dtype: int64

In [61]:
label_gender = LabelEncoder()
df['Gender'] = label_gender.fit_transform(df['Gender'])

label_severity = LabelEncoder()
df['Severity'] = label_severity.fit_transform(df['Severity'])

label_contact = LabelEncoder()
df['Contact_with_covid_patient'] = label_contact.fit_transform(df['Contact_with_covid_patient'])

In [62]:
df.head()

Age  Gender  fever  ...  Severity  Contact_with_covid_patient  Infected
0   10       1    102  ...         0                           0         0
1   20       1    103  ...         1                           1         1
2   55       2     99  ...         2                           0         0
3   37       0    100  ...         0                           2         1
4   45       1    101  ...         1                           2         1

[5 rows x 11 columns]

In [63]:
gender = df['Gender'].values
severity = df['Severity'].values
contact = df['Contact_with_covid_patient'].values

In [64]:
df.drop(columns=['Gender','Severity','Contact_with_covid_patient'], inplace=True)

In [65]:
df.head()

Age  fever  Bodypain  ...  Nasal_congestion  Sore_throat  Infected
0   10    102         1  ...                 0            1         0
1   20    103         1  ...                 0            0         1
2   55     99         0  ...                 1            1         0
3   37    100         0  ...                 0            0         1
4   45    101         1  ...                 1            0         1

[5 rows x 8 columns]

In [66]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [67]:
onehot_gender = OneHotEncoder()
gender = onehot_gender.fit_transform(gender.reshape(-1,1)).toarray()

In [68]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [69]:
onehot_severity = OneHotEncoder()
severity = onehot_severity.fit_transform(severity.reshape(-1,1)).toarray()

onehot_contact = OneHotEncoder()
contact = onehot_contact.fit_transform(contact.reshape(-1,1)).toarray()

In [70]:
X[0]

array([ 10, 102,   1,   0,   0,   0,   1])

In [71]:
X = np.c_[X, gender, severity, contact]

In [72]:
X[0]

array([ 10., 102.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   1.,
         0.,   0.,   1.,   0.,   0.])

In [73]:
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [74]:
X[0]

array([0.        , 0.66666667, 1.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        ])

In [75]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [76]:
x_train.shape

(1874, 16)

In [77]:
x_test.shape

(625, 16)

In [78]:
logistic = LogisticRegression()
logistic.fit(x_train, y_train)

LogisticRegression()

In [79]:
y_pred = logistic.predict(x_test)
accuracy_score(y_test, y_pred)

0.9408

In [80]:
confusion_matrix(y_test, y_pred)

array([[302,  20],
       [ 17, 286]])

In [81]:
from sklearn.metrics import classification_report

In [82]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       322
           1       0.93      0.94      0.94       303

    accuracy                           0.94       625
   macro avg       0.94      0.94      0.94       625
weighted avg       0.94      0.94      0.94       625



In [83]:
Age	= 34
fever	= 101
Bodypain	= 1
Runny_nose	= 0
Difficulty_in_breathing	= 0
Nasal_congestion	= 0
Sore_throat = 1

In [92]:
Gender = 'Male'
Severity = 'Moderate'
Contact = 'yes'

In [93]:
Gender = label_gender.transform([Gender])

In [94]:
Gender = onehot_gender.transform([Gender]).toarray()

In [95]:
Severity = label_severity.transform([Severity])
Severity = onehot_severity.transform([Severity]).toarray()

Contact = label_contact.transform([Contact])
Contact = onehot_contact.transform([Contact]).toarray()

In [98]:
testX = np.array([[Age,fever,Bodypain,Runny_nose,
                   Difficulty_in_breathing,Nasal_congestion]])

In [99]:
testX = np.c_[testX, Sore_throat,Gender,Severity,Contact]

In [100]:
testX

array([[ 34., 101.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   0.,
          1.,   0.,   0.,   0.,   1.]])

In [101]:
testX = minmax.transform(testX)

In [102]:
logistic.predict(testX)

array([1])