In [1]:
import numpy as np

In [2]:
np.array([3,4,6,6,2,5,82])

array([ 3,  4,  6,  6,  2,  5, 82])

In [3]:
np.array([3,4,67,6,3,34.3,24.4])

array([ 3. ,  4. , 67. ,  6. ,  3. , 34.3, 24.4])

In [4]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
np.linspace(2,25,15, retstep=True)

(array([ 2.        ,  3.64285714,  5.28571429,  6.92857143,  8.57142857,
        10.21428571, 11.85714286, 13.5       , 15.14285714, 16.78571429,
        18.42857143, 20.07142857, 21.71428571, 23.35714286, 25.        ]),
 1.6428571428571428)

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5, dtype=np.int)

array([1, 1, 1, 1, 1])

In [16]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.random()

0.7553276848106384

In [19]:
np.random.random(5)

array([0.253764  , 0.74516786, 0.73501029, 0.25060987, 0.27482455])

In [20]:
np.random.random([4,4])

array([[0.9663309 , 0.23022136, 0.95551612, 0.09072288],
       [0.69524538, 0.45373122, 0.14074437, 0.48679445],
       [0.35955109, 0.07805452, 0.25724538, 0.0947497 ],
       [0.14772022, 0.63066903, 0.78264893, 0.74752199]])

In [22]:
np.random.randint(1,100,5)

array([64, 83, 44, 36, 25])

In [23]:
np.random.randint(1,100,[4,5])

array([[22, 22, 74,  1, 44],
       [77, 35, 34, 36, 82],
       [49, 20, 26,  8, 85],
       [69, 99, 75, 85, 52]])

In [24]:
x = np.random.randint(1,100,10)

In [26]:
x

array([52, 33, 74, 11, 68, 34, 41,  5, 80, 35])

In [27]:
x[0]

52

In [28]:
x[-1]

35

In [29]:
x[0:5]

array([52, 33, 74, 11, 68])

In [30]:
x = np.random.randint(1,100,[4,6])

In [31]:
x

array([[98, 50, 41, 20, 59, 40],
       [31, 36, 68, 44, 30, 88],
       [16, 65, 21, 74, 28, 14],
       [11,  8, 13, 83, 98, 77]])

In [32]:
x[0]

array([98, 50, 41, 20, 59, 40])

In [33]:
x[0][0]

98

In [35]:
x[:, 0]

array([98, 31, 16, 11])

In [36]:
x[:, 0:1]

array([[98],
       [31],
       [16],
       [11]])

In [37]:
x[0,0]

98

In [38]:
x[0:2, 0:2]

array([[98, 50],
       [31, 36]])

In [39]:
x

array([[98, 50, 41, 20, 59, 40],
       [31, 36, 68, 44, 30, 88],
       [16, 65, 21, 74, 28, 14],
       [11,  8, 13, 83, 98, 77]])

In [43]:
x[[0,2], 0:2]

array([[98, 50],
       [16, 65]])

In [44]:
x[:, [0,2,4]]

array([[98, 41, 59],
       [31, 68, 30],
       [16, 21, 28],
       [11, 13, 98]])

In [45]:
np.shape(x)

(4, 6)

In [46]:
x.shape

(4, 6)

In [47]:
np.ndim(x)

2

In [48]:
x = x.flatten()

In [49]:
x

array([98, 50, 41, 20, 59, 40, 31, 36, 68, 44, 30, 88, 16, 65, 21, 74, 28,
       14, 11,  8, 13, 83, 98, 77])

In [50]:
np.min(x)

8

In [51]:
np.max(x)

98

In [52]:
np.sort(x)

array([ 8, 11, 13, 14, 16, 20, 21, 28, 30, 31, 36, 40, 41, 44, 50, 59, 65,
       68, 74, 77, 83, 88, 98, 98])

In [53]:
np.argmax(x)

0

In [54]:
np.argmin(x)

19

In [55]:
x[0]

98

In [56]:
x[0] = 100

In [57]:
x

array([100,  50,  41,  20,  59,  40,  31,  36,  68,  44,  30,  88,  16,
        65,  21,  74,  28,  14,  11,   8,  13,  83,  98,  77])

In [58]:
np.sum(x)

1115

In [59]:
np.mean(x)

46.458333333333336

In [60]:
np.median(x)

40.5

In [61]:
np.std(x)

28.486808594310613

In [62]:
np.var(x)

811.498263888889

In [66]:
np.reshape(x,(4,6))

array([[100,  50,  41,  20,  59,  40],
       [ 31,  36,  68,  44,  30,  88],
       [ 16,  65,  21,  74,  28,  14],
       [ 11,   8,  13,  83,  98,  77]])

In [72]:
x = np.reshape(x,(4,-1))

In [70]:
x

array([[100,  50,  41,  20,  59,  40],
       [ 31,  36,  68,  44,  30,  88],
       [ 16,  65,  21,  74,  28,  14],
       [ 11,   8,  13,  83,  98,  77]])

In [73]:
np.max(x)

100

In [74]:
np.max(x, axis=0)

array([100,  65,  68,  83,  98,  88])

In [75]:
np.max(x, axis=1)

array([100,  88,  74,  98])

In [77]:
np.mean(x, axis=0)

array([39.5 , 39.75, 35.75, 55.25, 53.75, 54.75])

In [88]:
# y = np.array([[2,4,5,2,55,2]])
np.vstack((x, [2,4,5,2,55,2]))

array([[100,  50,  41,  20,  59,  40],
       [ 31,  36,  68,  44,  30,  88],
       [ 16,  65,  21,  74,  28,  14],
       [ 11,   8,  13,  83,  98,  77],
       [  2,   4,   5,   2,  55,   2]])

In [86]:
y = np.array([[2],[4],[5],[2]])
np.hstack((x, y))

array([[100,  50,  41,  20,  59,  40,   2],
       [ 31,  36,  68,  44,  30,  88,   4],
       [ 16,  65,  21,  74,  28,  14,   5],
       [ 11,   8,  13,  83,  98,  77,   2]])

In [89]:
import sys

In [90]:
sys.getsizeof([])

72

In [92]:
sys.getsizeof(np.array([]))

96

In [99]:
sys.getsizeof([i for i in range(10000)])

87632

In [100]:
sys.getsizeof(np.array([i for i in range(10000)]))

80096